services:
  mysql:
    image: mysql:8.0
    container_name: db_hospital_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: db_hospital_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  login:
    build: ./microservicio-login
    container_name: api_login
    ports:
      - "3001:3001"
    depends_on:
      mysql:
        condition: service_healthy

  medicos:
    build: ./microservicio-medicos
    container_name: api_medicos
    ports:
      - "3002:3002"
    depends_on:
      mysql:
        condition: service_healthy

  citas:
    build: ./microservicio-citas
    container_name: api_citas
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  proxy:
    image: nginx:alpine
    container_name: api_gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      login:
        condition: service_started
      medicos:
        condition: service_started
      citas:
        condition: service_started

volumes:
  mysql_data:
  mongo_data: